CREATE DATABASE IF NOT EXISTS inventarioDB;

USE inventarioDB;
CREATE TABLE `inventariodb`.`users` (
  `id` VARCHAR(45) GENERATED ALWAYS AS () VIRTUAL,
  `name` VARCHAR(45) NOT NULL,
  `user_name` VARCHAR(45) NOT NULL,
  `telephone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` VARCHAR(45) NOT NULL DEFAULT 'DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;
